version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql 
    volumes:
      - .:/usr/app  # Monta o diretório atual do host no contêiner
      - /usr/app/node_modules  # Monta o diretório node_modules do contêiner para evitar problemas de permissão

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
